# Generated by Django 5.2.16 on 2026-07-13 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='core.sucursal')),
            ],
            options={
                'verbose_name_plural': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INI', 'Carga inicial'), ('COM', 'Compra'), ('VEN', 'Venta'), ('AJU', 'Ajuste'), ('TRA', 'Transferencia')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positiva entra, negativa sale', max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_promedio_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_resultante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Documento origen (factura, OC, ajuste)', max_length=80)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='cantidad_distinta_de_cero'), models.CheckConstraint(condition=models.Q(('stock_resultante__gte', 0)), name='kardex_stock_no_negativo')],
            },
        ),
    ]
