# Generated by Django 5.2.16 on 2026-07-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimientoinventario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INI', 'Carga inicial'), ('COM', 'Compra'), ('VEN', 'Venta'), ('REG', 'Regalía / promoción'), ('DEV', 'Devolución / anulación'), ('AJU', 'Ajuste'), ('TRA', 'Transferencia')], max_length=3),
        ),
    ]
