# Generated by Django 5.2.16 on 2026-07-28 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cambioprecio'),
        ('inventario', '0003_alter_movimientoinventario_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'fecha'], name='kardex_prod_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='kardex_fecha_idx'),
        ),
    ]
