# Generated by Django 5.2.16 on 2026-07-28 22:39
#
# Auditoría 2026-07-28, hallazgo BE-09: hace explícito el supuesto de "una
# bodega por sucursal" que hasta ahora vivía implícito en un .first().

from django.db import migrations, models


def marcar_bodega_principal(apps, schema_editor):
    """Marca como principal la bodega existente de cada sucursal.

    Preserva EXACTAMENTE el comportamiento anterior: el código tomaba la
    primera bodega de la sucursal, así que se marca esa misma (la de menor
    id). Después de esta migración las ventas siguen saliendo de donde salían;
    la diferencia es que ahora está declarado en vez de ser un accidente del
    orden de consulta.
    """
    Bodega = apps.get_model("inventario", "Bodega")
    vistas = set()
    for bodega in Bodega.objects.order_by("sucursal_id", "id"):
        if bodega.sucursal_id in vistas:
            continue
        vistas.add(bodega.sucursal_id)
        bodega.principal = True
        bodega.save(update_fields=["principal"])


def desmarcar(apps, schema_editor):
    """Reversa: quita la marca. El código vuelve a caer al .first() histórico."""
    Bodega = apps.get_model("inventario", "Bodega")
    Bodega.objects.filter(principal=True).update(principal=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog_audit_obj_idx_and_more'),
        ('inventario', '0004_movimientoinventario_kardex_prod_fecha_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='principal',
            field=models.BooleanField(default=False, help_text='De esta bodega salen las ventas. Solo puede haber una por sucursal.', verbose_name='bodega principal'),
        ),
        # El paso de datos va ANTES de la restricción: si hubiera dos bodegas
        # marcadas como principales en la misma sucursal, la restricción debe
        # fallar en la migración —donde se ve— y no en medio de una venta.
        migrations.RunPython(marcar_bodega_principal, desmarcar),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('sucursal',), name='una_sola_bodega_principal_por_sucursal'),
        ),
    ]
