# Generated by Django 5.2.17 on 2026-10-03 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0011_deshacer_marcado_etiquetas_27sep"),
        ("inventario", "0005_bodega_principal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agotamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_salida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INI", "Carga inicial"),
                            ("COM", "Compra"),
                            ("VEN", "Venta"),
                            ("REG", "Regalía / promoción"),
                            ("DEV", "Devolución / anulación"),
                            ("AJU", "Ajuste"),
                            ("TRA", "Transferencia"),
                        ],
                        max_length=3,
                    ),
                ),
                ("fecha", models.DateTimeField(help_text="Cuándo quedó en cero")),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PEN", "Por decidir"),
                            ("PED", "Volver a pedir"),
                            ("NO", "No comprar más"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("decidido_en", models.DateTimeField(blank=True, null=True)),
                ("repuesto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "decidido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventario.movimientoinventario",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agotamientos",
                        to="catalogo.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto agotado",
                "verbose_name_plural": "productos agotados",
                "ordering": ["-fecha", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("repuesto_en__isnull", True)),
                        fields=("producto",),
                        name="un_agotamiento_abierto_por_producto",
                    )
                ],
            },
        ),
    ]
