# Generated by Django 5.2.17 on 2026-08-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_chequeointegridad'),
        ('ventas', '0007_facturaventa_fv_creado_en_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(help_text='Consecutivo interno del ERP (texto). NO es el consecutivo de 20 dígitos que exige la clave de Hacienda.', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del comprobante ante Hacienda. Vacía hasta que exista el generador de XML (requiere el Anexo v4.4 + XSD oficiales).', max_length=50)),
                ('estado', models.CharField(choices=[('PEF', 'Pendiente de firma'), ('FIR', 'Firmado, pendiente de envío'), ('ENV', 'Enviado, sin respuesta de Hacienda'), ('ACE', 'Aceptado por Hacienda'), ('REC', 'Rechazado por Hacienda'), ('ERR', 'Reintentos agotados, requiere atención manual')], default='PEF', max_length=3)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_hacienda', models.TextField(blank=True, help_text='Detalle de aceptación o rechazo, tal cual lo devuelve Hacienda')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('ruta_xml_firmado', models.CharField(blank=True, max_length=250)),
                ('ruta_xml_respuesta_hacienda', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('factura_venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_electronica', to='ventas.facturaventa')),
            ],
            options={
                'verbose_name': 'factura electrónica',
                'verbose_name_plural': 'facturas electrónicas',
            },
        ),
        migrations.CreateModel(
            name='ReciboElectronicoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(help_text='Consecutivo interno del ERP (texto). NO es el consecutivo de 20 dígitos que exige la clave de Hacienda.', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del comprobante ante Hacienda. Vacía hasta que exista el generador de XML (requiere el Anexo v4.4 + XSD oficiales).', max_length=50)),
                ('estado', models.CharField(choices=[('PEF', 'Pendiente de firma'), ('FIR', 'Firmado, pendiente de envío'), ('ENV', 'Enviado, sin respuesta de Hacienda'), ('ACE', 'Aceptado por Hacienda'), ('REC', 'Rechazado por Hacienda'), ('ERR', 'Reintentos agotados, requiere atención manual')], default='PEF', max_length=3)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_hacienda', models.TextField(blank=True, help_text='Detalle de aceptación o rechazo, tal cual lo devuelve Hacienda')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('ruta_xml_firmado', models.CharField(blank=True, max_length=250)),
                ('ruta_xml_respuesta_hacienda', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('factura_electronica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_pago', to='facturacion_electronica.facturaelectronica')),
            ],
            options={
                'verbose_name': 'recibo electrónico de pago',
                'verbose_name_plural': 'recibos electrónicos de pago',
            },
        ),
        migrations.CreateModel(
            name='TiqueteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(help_text='Consecutivo interno del ERP (texto). NO es el consecutivo de 20 dígitos que exige la clave de Hacienda.', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del comprobante ante Hacienda. Vacía hasta que exista el generador de XML (requiere el Anexo v4.4 + XSD oficiales).', max_length=50)),
                ('estado', models.CharField(choices=[('PEF', 'Pendiente de firma'), ('FIR', 'Firmado, pendiente de envío'), ('ENV', 'Enviado, sin respuesta de Hacienda'), ('ACE', 'Aceptado por Hacienda'), ('REC', 'Rechazado por Hacienda'), ('ERR', 'Reintentos agotados, requiere atención manual')], default='PEF', max_length=3)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_hacienda', models.TextField(blank=True, help_text='Detalle de aceptación o rechazo, tal cual lo devuelve Hacienda')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('ruta_xml_firmado', models.CharField(blank=True, max_length=250)),
                ('ruta_xml_respuesta_hacienda', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('factura_venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tiquete_electronico', to='ventas.facturaventa')),
            ],
            options={
                'verbose_name': 'tiquete electrónico',
                'verbose_name_plural': 'tiquetes electrónicos',
            },
        ),
        migrations.CreateModel(
            name='NotaDebitoElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(help_text='Consecutivo interno del ERP (texto). NO es el consecutivo de 20 dígitos que exige la clave de Hacienda.', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del comprobante ante Hacienda. Vacía hasta que exista el generador de XML (requiere el Anexo v4.4 + XSD oficiales).', max_length=50)),
                ('estado', models.CharField(choices=[('PEF', 'Pendiente de firma'), ('FIR', 'Firmado, pendiente de envío'), ('ENV', 'Enviado, sin respuesta de Hacienda'), ('ACE', 'Aceptado por Hacienda'), ('REC', 'Rechazado por Hacienda'), ('ERR', 'Reintentos agotados, requiere atención manual')], default='PEF', max_length=3)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_hacienda', models.TextField(blank=True, help_text='Detalle de aceptación o rechazo, tal cual lo devuelve Hacienda')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('ruta_xml_firmado', models.CharField(blank=True, max_length=250)),
                ('ruta_xml_respuesta_hacienda', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('factura_electronica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='facturacion_electronica.facturaelectronica')),
                ('tiquete_electronico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_debito', to='facturacion_electronica.tiqueteelectronico')),
            ],
            options={
                'verbose_name': 'nota de débito electrónica',
                'verbose_name_plural': 'notas de débito electrónicas',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('factura_electronica__isnull', False), ('tiquete_electronico__isnull', True)), models.Q(('factura_electronica__isnull', True), ('tiquete_electronico__isnull', False)), _connector='OR'), name='nd_referencia_exactamente_un_comprobante')],
            },
        ),
        migrations.CreateModel(
            name='NotaCreditoElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(help_text='Consecutivo interno del ERP (texto). NO es el consecutivo de 20 dígitos que exige la clave de Hacienda.', max_length=20, unique=True)),
                ('clave', models.CharField(blank=True, help_text='Clave del comprobante ante Hacienda. Vacía hasta que exista el generador de XML (requiere el Anexo v4.4 + XSD oficiales).', max_length=50)),
                ('estado', models.CharField(choices=[('PEF', 'Pendiente de firma'), ('FIR', 'Firmado, pendiente de envío'), ('ENV', 'Enviado, sin respuesta de Hacienda'), ('ACE', 'Aceptado por Hacienda'), ('REC', 'Rechazado por Hacienda'), ('ERR', 'Reintentos agotados, requiere atención manual')], default='PEF', max_length=3)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_hacienda', models.TextField(blank=True, help_text='Detalle de aceptación o rechazo, tal cual lo devuelve Hacienda')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('ruta_xml_firmado', models.CharField(blank=True, max_length=250)),
                ('ruta_xml_respuesta_hacienda', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.empresa')),
                ('factura_electronica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion_electronica.facturaelectronica')),
                ('tiquete_electronico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion_electronica.tiqueteelectronico')),
            ],
            options={
                'verbose_name': 'nota de crédito electrónica',
                'verbose_name_plural': 'notas de crédito electrónicas',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('factura_electronica__isnull', False), ('tiquete_electronico__isnull', True)), models.Q(('factura_electronica__isnull', True), ('tiquete_electronico__isnull', False)), _connector='OR'), name='nc_referencia_exactamente_un_comprobante')],
            },
        ),
    ]
