# Generated by Django 5.2.16 on 2026-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta relativa dentro de media/ (ej. productos/75564.png)', max_length=200),
        ),
    ]
