# Generated by Django 5.2.16 on 2026-07-21 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_al_momento', models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio del producto cuando se cambió el precio, para ver el margen histórico', max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_precio', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de precio',
                'verbose_name_plural': 'cambios de precio',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
