# Generated by Django 5.2.17 on 2026-08-29 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_descripcion_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cabys',
            field=models.CharField(blank=True, help_text='13 dígitos del Catálogo de Bienes y Servicios de Hacienda. Vacío hasta que se confirme a mano — no se inventa.', max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'El código CABYS son 13 dígitos numéricos, tal cual lo publica Hacienda (con ceros a la izquierda si los tiene). No se inventa: se copia del catálogo oficial https://www.hacienda.go.cr/consultacabys/')], verbose_name='código CABYS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, help_text='Marca del producto (ej. Royal Canin, Pedigree)', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_unidad',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('g', 'g'), ('lb', 'lb'), ('oz', 'oz'), ('l', 'l'), ('ml', 'ml'), ('un', 'unidad')], max_length=2),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_valor',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Contenido neto del empaque (ej. 15 para una bolsa de 15 kg)', max_digits=8, null=True),
        ),
    ]
