# Generated by Django 5.2.17 on 2026-09-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0007_iva_general_en_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="etiqueta_impresa_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
