# Generated by Django 5.2.17 on 2026-09-27 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_producto_destacado_home_orden_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador estable, ej. nutrisource-adult-chicken-rice', max_length=80, unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('linea', models.CharField(blank=True, help_text='Línea dentro de la marca, ej. Grain Free, Exclusive', max_length=80)),
                ('nombre', models.CharField(help_text='Nombre oficial de la fórmula, como lo publica el fabricante', max_length=160)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('tipo', models.CharField(choices=[('seco', 'Alimento seco'), ('humedo', 'Alimento húmedo'), ('snack', 'Snack o premio')], max_length=10)),
                ('etapas', models.JSONField(blank=True, default=list, help_text='Claves de catalogo/alimentos.py ETAPAS')),
                ('tamanos_raza', models.JSONField(blank=True, default=list, help_text='Claves de TAMANOS_RAZA')),
                ('necesidades', models.JSONField(blank=True, default=list, help_text='Claves de NECESIDADES que declara el fabricante')),
                ('proteina_principal', models.CharField(blank=True, help_text='Primer ingrediente proteico, ej. Pollo', max_length=60)),
                ('sabor', models.CharField(blank=True, max_length=120)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('ingredientes', models.TextField(blank=True)),
                ('aditivos', models.TextField(blank=True, help_text='Vitaminas, minerales y aditivos, tal como los declara el fabricante')),
                ('analisis', models.JSONField(blank=True, default=list)),
                ('kcal_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Energía metabolizable por kg', max_digits=7, null=True)),
                ('kcal_unidad', models.DecimalField(blank=True, decimal_places=2, help_text='Por taza, lata o sobre', max_digits=8, null=True)),
                ('unidad_kcal', models.CharField(blank=True, help_text="Qué es la 'unidad' de kcal_unidad: taza, lata, sobre", max_length=20)),
                ('guia_alimentacion', models.JSONField(blank=True, default=dict)),
                ('fuentes', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('sin_investigar', 'Sin investigar'), ('parcial', 'Parcial'), ('verificado', 'Verificado'), ('revisar', 'Requiere revisión')], default='sin_investigar', max_length=16)),
                ('verificado_en', models.DateField(blank=True, help_text='Última vez que se contrastó contra la fuente oficial', null=True)),
                ('notas_internas', models.TextField(blank=True, help_text='Dudas, diferencias entre fuentes, qué falta. No se publica.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ficha de alimento',
                'verbose_name_plural': 'fichas de alimento',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_alimento',
            field=models.ForeignKey(blank=True, help_text='Fórmula a la que pertenece esta presentación (solo alimentos).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.fichaalimento'),
        ),
    ]
