# Generated by Django 5.2.16 on 2026-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='factor_rts',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Factor RTS que Hacienda asigna a tu actividad (ej. 0.02 = 2% de las compras). Confirmalo con tu contador o en TRIBU-CR. 0 si aún no lo sabés.', max_digits=6),
        ),
    ]
