# Generated by Django 5.2.16 on 2026-07-27 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_factor_rts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('error', models.TextField(blank=True, help_text='Si la llamada a Claude falló, el detalle queda acá')),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mensajes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensaje de chat',
                'verbose_name_plural': 'mensajes de chat',
                'ordering': ['-creado_en'],
            },
        ),
    ]
