# Generated by Django 5.2.16 on 2026-07-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='identificacion',
            field=models.CharField(blank=True, help_text='Cédula jurídica (o física, si sos persona física con actividad lucrativa). La necesita cualquier cliente empresa que quiera respaldar la compra ante Hacienda con una Factura Electrónica de Compra (FEC), aunque vos no emitas electrónico todavía.', max_length=20),
        ),
    ]
