# Generated by Django 5.2.16 on 2026-07-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auditlog_audit_obj_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeoIntegridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisados', models.PositiveIntegerField(default=0)),
                ('descuadres', models.PositiveIntegerField(default=0)),
                ('detalle', models.TextField(blank=True, help_text='Las diferencias encontradas, si las hubo')),
            ],
            options={
                'verbose_name': 'chequeo de integridad',
                'verbose_name_plural': 'chequeos de integridad',
                'ordering': ['-fecha'],
            },
        ),
    ]
