# Generated by Django 5.2.17 on 2026-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chequeointegridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='canton',
            field=models.CharField(blank=True, max_length=60, verbose_name='cantón'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_actividad',
            field=models.CharField(blank=True, help_text='El que aparece en la inscripción ante Hacienda. Lo confirma el contador.', max_length=10, verbose_name='código de actividad económica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo del emisor en los comprobantes', max_length=254),
        ),
        migrations.AddField(
            model_name='empresa',
            name='distrito',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='empresa',
            name='establecimiento',
            field=models.CharField(default='001', help_text='Número de local para la numeración de Hacienda (3 dígitos)', max_length=3),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='empresa',
            name='otras_senas',
            field=models.CharField(blank=True, max_length=250, verbose_name='otras señas'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='terminal',
            field=models.CharField(default='00001', help_text='Número de caja para la numeración de Hacienda (5 dígitos)', max_length=5),
        ),
    ]
