# Generated by Django 5.2.16 on 2026-07-13 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('catalogo', '0001_initial'),
        ('core', '0002_auditlog_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('EMI', 'Emitida'), ('ANU', 'Anulada')], default='EMI', max_length=3)),
                ('medio_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('SIN', 'SINPE Móvil')], max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=200)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='ventas.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'factura de venta',
                'verbose_name_plural': 'facturas de venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='FV', max_length=4)),
                ('siguiente', models.PositiveIntegerField(default=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo'), name='consecutivo_unico')],
            },
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.facturaventa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'línea de venta',
                'verbose_name_plural': 'líneas de venta',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_venta_positiva')],
            },
        ),
    ]
