# Generated by Django 5.2.16 on 2026-07-21 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = no se le vende a crédito', max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deuda pendiente (denormalizado)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='medio_pago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('SIN', 'SINPE Móvil'), ('CRE', 'Crédito (CxC)')], max_length=3),
        ),
        migrations.CreateModel(
            name='DocumentoCxC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('ANU', 'Anulado')], default='PEN', max_length=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cxc', to='ventas.cliente')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cxc', to='ventas.facturaventa')),
            ],
            options={
                'verbose_name': 'documento por cobrar',
                'verbose_name_plural': 'documentos por cobrar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('SIN', 'SINPE Móvil'), ('TRA', 'Transferencia')], default='EFE', max_length=3)),
                ('referencia', models.CharField(blank=True, max_length=60)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='ventas.documentocxc')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='abono_positivo')],
            },
        ),
    ]
