# Generated by Django 5.2.16 on 2026-07-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cxc_y_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de descuentos de las líneas', max_digits=12),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en colones sobre esta línea', max_digits=12),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='es_regalia',
            field=models.BooleanField(default=False, help_text='Producto entregado gratis: sin ingreso, pero su costo sale a gasto'),
        ),
    ]
