# Generated by Django 5.2.16 on 2026-07-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_facturaventa_descuento_lineaventa_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaventa',
            name='descuento',
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto en colones aplicado (calculado automáticamente)', max_digits=12),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (0-100)', max_digits=5),
        ),
    ]
