# Generated by Django 5.2.16 on 2026-07-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_facturaventa_anulada_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('motivo', models.CharField(max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Monto reembolsado (no incluye líneas de regalía)', max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.facturaventa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'devolución de venta',
                'verbose_name_plural': 'devoluciones de venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.devolucionventa')),
                ('linea_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.lineaventa')),
            ],
            options={
                'verbose_name': 'línea de devolución',
                'verbose_name_plural': 'líneas de devolución',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_devolucion_positiva')],
            },
        ),
    ]
