# Generated by Django 5.2.16 on 2026-07-28 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0006_empresa_identificacion'),
        ('ventas', '0006_devolucionventa_lineadevolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['creado_en'], name='fv_creado_en_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaventa',
            index=models.Index(fields=['empresa', 'estado', 'creado_en'], name='fv_emp_est_fecha_idx'),
        ),
    ]
