# Generated by Django 5.2.17 on 2026-09-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_facturaventa_fv_creado_en_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canton',
            field=models.CharField(blank=True, max_length=60, verbose_name='cantón'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='distrito',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('FIS', 'Cédula física'), ('JUR', 'Cédula jurídica'), ('DIM', 'DIMEX'), ('NIT', 'NITE'), ('EXT', 'Extranjero / pasaporte')], max_length=3),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='clave_pos',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='cabys',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='impuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de la línea sin IVA', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lineaventa',
            name='tarifa_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='medio_pago',
            field=models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('SIN', 'SINPE Móvil'), ('CRE', 'Crédito (CxC)'), ('MIX', 'Pago mixto')], max_length=3),
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('SIN', 'SINPE Móvil'), ('CRE', 'Crédito (CxC)'), ('MIX', 'Pago mixto')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.facturaventa')),
            ],
            options={
                'verbose_name': 'pago de venta',
                'verbose_name_plural': 'pagos de venta',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_venta_positivo')],
            },
        ),
    ]
