# Generated by Django 5.2.17 on 2026-08-29 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0005_producto_cabys_producto_marca_producto_peso_unidad_and_more'),
        ('core', '0008_chequeointegridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PAG', 'Pago confirmado'), ('PRE', 'En preparación'), ('DES', 'Despachado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PAG', max_length=3)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_identificacion', models.CharField(blank=True, max_length=20)),
                ('cliente_telefono', models.CharField(max_length=30)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('direccion_texto', models.CharField(help_text='Dirección escrita, la que necesita el courier', max_length=300)),
                ('direccion_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referencia_pago', models.CharField(blank=True, help_text='ID de la transacción en la pasarela de pago, para conciliar y para la idempotencia del webhook', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
            },
        ),
        migrations.CreateModel(
            name='CambioEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PAG', 'Pago confirmado'), ('PRE', 'En preparación'), ('DES', 'Despachado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3)),
                ('estado_nuevo', models.CharField(choices=[('PAG', 'Pago confirmado'), ('PRE', 'En preparación'), ('DES', 'Despachado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], max_length=3)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'cambio de estado de pedido',
                'verbose_name_plural': 'cambios de estado de pedido',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_carrito', models.CharField(db_index=True, help_text='Identificador opaco del carrito del navegador', max_length=64)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_stock', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'reserva de stock',
                'verbose_name_plural': 'reservas de stock',
            },
        ),
        migrations.CreateModel(
            name='AvisoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('notificado_en', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_disponibilidad', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'aviso de disponibilidad',
                'verbose_name_plural': 'avisos de disponibilidad',
                'constraints': [models.UniqueConstraint(fields=('producto', 'email'), name='aviso_unico_por_producto_y_correo')],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['empresa', 'estado', 'creado_en'], name='pedido_emp_est_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='lineapedido',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_pedido_positiva'),
        ),
        migrations.AddConstraint(
            model_name='reservastock',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_reserva_positiva'),
        ),
        migrations.AddConstraint(
            model_name='reservastock',
            constraint=models.UniqueConstraint(fields=('producto', 'token_carrito'), name='reserva_unica_por_producto_y_carrito'),
        ),
    ]
