# Generated by Django 5.2.17 on 2026-08-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chequeointegridad'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_pago', ''), _negated=True), fields=('empresa', 'referencia_pago'), name='pedido_referencia_pago_unica'),
        ),
    ]
