# Generated by Django 5.2.16 on 2026-07-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('origen', models.CharField(choices=[('VEN', 'Venta'), ('COS', 'Costo de venta'), ('COB', 'Cobro (abono CxC)'), ('ANU', 'Anulación'), ('MAN', 'Manual')], max_length=3)),
                ('referencia', models.CharField(blank=True, help_text='Documento que lo originó', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=120)),
                ('naturaleza', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('Q', 'Patrimonio'), ('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('movimiento', models.BooleanField(default=True, help_text='Si acepta asientos directos (cuenta de detalle)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='core.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'línea de asiento',
                'verbose_name_plural': 'líneas de asiento',
            },
        ),
        migrations.AddConstraint(
            model_name='cuentacontable',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='cuenta_codigo_unico'),
        ),
        migrations.AddConstraint(
            model_name='lineaasiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debe__gt', 0), ('haber', 0)), models.Q(('haber__gt', 0), ('debe', 0)), _connector='OR'), name='linea_debe_o_haber'),
        ),
    ]
