# Generated by Django 5.2.16 on 2026-07-21 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('core', '0003_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField(help_text='Se bloquea todo lo que tenga esta fecha o anterior')),
                ('nota', models.CharField(blank=True, help_text="Ej. 'IVA I trimestre declarado'", max_length=200)),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('reabierto_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reapertura', models.CharField(blank=True, max_length=200)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_hechos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='core.empresa')),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_reabiertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cierre de período',
                'verbose_name_plural': 'cierres de período',
                'ordering': ['-fecha_cierre', '-id'],
            },
        ),
    ]
