# Generated by Django 5.2.16 on 2026-07-28 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cierreperiodo'),
        ('core', '0006_empresa_identificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['fecha'], name='asiento_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['empresa', 'fecha'], name='asiento_emp_fecha_idx'),
        ),
    ]
