# Generated by Django 5.2.17 on 2026-09-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrabajoImpresion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tiquete", "Tiquete de venta"),
                            ("etiqueta", "Etiqueta de producto"),
                            ("prueba", "Impresión de prueba"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("crudo", "Bytes crudos (ESC/POS)"),
                            ("imagen", "Imagen por el driver"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "impresora",
                    models.CharField(
                        help_text="Nombre de la cola en Windows, tal como la ve la computadora de la tienda.",
                        max_length=120,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=120)),
                (
                    "contenido",
                    models.BinaryField(
                        help_text="Los bytes a imprimir: ESC/POS si el formato es crudo, PNG si es imagen."
                    ),
                ),
                ("ancho_mm", models.FloatField(blank=True, null=True)),
                ("alto_mm", models.FloatField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Esperando al agente"),
                            ("tomado", "El agente lo tomó"),
                            ("impreso", "Impreso"),
                            ("error", "Falló"),
                            ("vencido", "Venció sin imprimirse"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "detalle",
                    models.TextField(
                        blank=True, help_text="El mensaje de error, si falló."
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("vence_en", models.DateTimeField()),
                ("tomado_en", models.DateTimeField(blank=True, null=True)),
                ("terminado_en", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "trabajo de impresión",
                "verbose_name_plural": "trabajos de impresión",
                "ordering": ["creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado", "creado_en"],
                        name="impresion_t_estado_309b97_idx",
                    )
                ],
            },
        ),
    ]
