# Generated by Django 5.2.16 on 2026-07-13 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditlog_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABI', 'Abierta'), ('CER', 'Cerrada')], default='ABI', max_length=3)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('monto_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to='core.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de caja',
                'verbose_name_plural': 'sesiones de caja',
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APE', 'Apertura'), ('VEN', 'Venta en efectivo'), ('ING', 'Ingreso manual'), ('EGR', 'Egreso manual'), ('ANU', 'Devolución por anulación')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.sesioncaja')),
            ],
            options={
                'verbose_name': 'movimiento de caja',
                'verbose_name_plural': 'movimientos de caja',
                'ordering': ['-fecha', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto', 0), _negated=True), name='monto_caja_distinto_de_cero')],
            },
        ),
    ]
