# Generated by Django 5.2.17 on 2026-09-26 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='sinpe_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='SINPE recibido'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='sinpe_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='tarjeta_contado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='tarjeta según datáfono'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='tarjeta_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
