# Generated by Django 5.2.16 on 2026-07-21 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0002_auditlog_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, help_text='Deuda con el proveedor (CxP, denormalizado)', max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='core.empresa')),
            ],
            options={
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('factura_proveedor', models.CharField(blank=True, help_text='N.º de factura del proveedor', max_length=40)),
                ('estado', models.CharField(choices=[('BOR', 'Borrador'), ('REC', 'Recibida'), ('ANU', 'Anulada')], default='BOR', max_length=3)),
                ('forma_pago', models.CharField(choices=[('CON', 'Contado (Bancos)'), ('CRE', 'Crédito del proveedor (CxP)')], default='CON', max_length=3)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('recibida_en', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LineaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'línea de compra',
                'verbose_name_plural': 'líneas de compra',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_compra_positiva')],
            },
        ),
    ]
