# Generated by Django 5.2.16 on 2026-07-28 03:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_anulada_en_compra_anulada_por_and_more'),
        ('core', '0006_empresa_identificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['recibida_en'], name='compra_recibida_idx'),
        ),
        migrations.AddIndex(
            model_name='compra',
            index=models.Index(fields=['empresa', 'estado', 'recibida_en'], name='compra_emp_est_rec_idx'),
        ),
    ]
