# Generated by Django 5.2.17 on 2026-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0004_lineacompra_cantidad_bonificada"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="iva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="IVA que trae la factura electrónica del proveedor. 0 si no hay factura.",
                max_digits=12,
                verbose_name="IVA de la factura",
            ),
        ),
    ]
